"""Add voice analysis tables

Revision ID: 61303a26c0fc
Revises: 97d70356e1aa
Create Date: 2025-12-19 12:19:37.410751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61303a26c0fc'
down_revision = '97d70356e1aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotional_profiles',
    sa.Column('voice_profile_id', sa.String(), nullable=False),
    sa.Column('valence', sa.Float(), nullable=True),
    sa.Column('arousal', sa.Float(), nullable=True),
    sa.Column('dominance', sa.Float(), nullable=True),
    sa.Column('happiness_score', sa.Float(), nullable=True),
    sa.Column('sadness_score', sa.Float(), nullable=True),
    sa.Column('anger_score', sa.Float(), nullable=True),
    sa.Column('fear_score', sa.Float(), nullable=True),
    sa.Column('surprise_score', sa.Float(), nullable=True),
    sa.Column('disgust_score', sa.Float(), nullable=True),
    sa.Column('breathiness', sa.Float(), nullable=True),
    sa.Column('roughness', sa.Float(), nullable=True),
    sa.Column('strain', sa.Float(), nullable=True),
    sa.Column('confidence_interval', sa.Float(), nullable=True),
    sa.Column('analysis_reliability', sa.Float(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prosody_features',
    sa.Column('voice_profile_id', sa.String(), nullable=False),
    sa.Column('syllable_duration_mean', sa.Float(), nullable=True),
    sa.Column('syllable_duration_std', sa.Float(), nullable=True),
    sa.Column('pause_duration_mean', sa.Float(), nullable=True),
    sa.Column('pause_duration_std', sa.Float(), nullable=True),
    sa.Column('stress_pattern_entropy', sa.Float(), nullable=True),
    sa.Column('primary_stress_ratio', sa.Float(), nullable=True),
    sa.Column('pitch_contour_complexity', sa.Float(), nullable=True),
    sa.Column('pitch_range_semitones', sa.Float(), nullable=True),
    sa.Column('declination_slope', sa.Float(), nullable=True),
    sa.Column('excitement_score', sa.Float(), nullable=True),
    sa.Column('calmness_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('pitch_contour', sa.JSON(), nullable=True),
    sa.Column('energy_contour', sa.JSON(), nullable=True),
    sa.Column('timing_features', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice_models',
    sa.Column('voice_profile_id', sa.String(), nullable=False),
    sa.Column('reference_audio_id', sa.String(), nullable=False),
    sa.Column('model_path', sa.String(), nullable=False),
    sa.Column('config_path', sa.String(), nullable=True),
    sa.Column('voice_characteristics', sa.JSON(), nullable=True),
    sa.Column('model_type', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('training_duration', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('validation_loss', sa.Float(), nullable=True),
    sa.Column('model_size_mb', sa.Float(), nullable=True),
    sa.Column('inference_time_ms', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ANALYZING', 'READY', 'FAILED', name='voicemodelstatus'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice_profiles',
    sa.Column('reference_audio_id', sa.String(), nullable=False),
    sa.Column('f0_mean', sa.Float(), nullable=True),
    sa.Column('f0_std', sa.Float(), nullable=True),
    sa.Column('f0_min', sa.Float(), nullable=True),
    sa.Column('f0_max', sa.Float(), nullable=True),
    sa.Column('formant_frequencies', sa.JSON(), nullable=True),
    sa.Column('spectral_centroid_mean', sa.Float(), nullable=True),
    sa.Column('spectral_rolloff_mean', sa.Float(), nullable=True),
    sa.Column('spectral_bandwidth_mean', sa.Float(), nullable=True),
    sa.Column('zero_crossing_rate_mean', sa.Float(), nullable=True),
    sa.Column('mfcc_features', sa.JSON(), nullable=True),
    sa.Column('speech_rate', sa.Float(), nullable=True),
    sa.Column('pause_frequency', sa.Float(), nullable=True),
    sa.Column('emphasis_variance', sa.Float(), nullable=True),
    sa.Column('energy_mean', sa.Float(), nullable=True),
    sa.Column('energy_variance', sa.Float(), nullable=True),
    sa.Column('pitch_variance', sa.Float(), nullable=True),
    sa.Column('signal_to_noise_ratio', sa.Float(), nullable=True),
    sa.Column('voice_activity_ratio', sa.Float(), nullable=True),
    sa.Column('analysis_duration', sa.Float(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('total_frames', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('features_file_path', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_audio_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voice_profiles')
    op.drop_table('voice_models')
    op.drop_table('prosody_features')
    op.drop_table('emotional_profiles')
    # ### end Alembic commands ###