"""Initial migration

Revision ID: 97d70356e1aa
Revises: 
Create Date: 2025-12-18 23:11:16.372547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97d70356e1aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reference_audio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_audio',
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('filename', sa.VARCHAR(), nullable=False),
    sa.Column('file_path', sa.VARCHAR(), nullable=False),
    sa.Column('duration', sa.FLOAT(), nullable=True),
    sa.Column('sample_rate', sa.INTEGER(), nullable=True),
    sa.Column('format', sa.VARCHAR(), nullable=False),
    sa.Column('file_size', sa.INTEGER(), nullable=False),
    sa.Column('processing_status', sa.VARCHAR(length=10), nullable=True),
    sa.Column('voice_profile_id', sa.VARCHAR(), nullable=True),
    sa.Column('error_message', sa.VARCHAR(), nullable=True),
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###